### PR TITLE
Moves project to eclipse name space

### LINKED ISSUE #1: Tasks before migration to e4
Rename plug-in to Eclipse name space.

org.eclipse.ui.regex

### PR DESCRIPTION
**Pull request by fapdash**
closes #1

* changes base package from 'com.brosinski.eclipse.regex' to
'org.eclipse.ui.regex'

### CODE REVIEW

**Review by daweiser — APPROVED** [review]
Looks good!

**Comment by vogella** [comment]
Looks good. I suggest to upload this code to the IP check of the foundation
and do any additional fix after the migration.

Fabian and David: ok for you?

Am 29.05.2017 11:39 vorm. schrieb "David" <notifications@github.com>:

**Comment by fapdash** [comment]
I think that's a good idea. Please go ahead. :+1:

**Comment by daweiser** [comment]
Jep, +1

**Pull request merged**
